language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

  allow_failures:
    - rust: nightly

cache: cargo

script:
  - cargo update
  - ./.travis/run.sh "$TRAVIS_RUST_VERSION"