[package]
name = "smartcrop"
description="Clone of smartcrop library in JavaScript"
license="GPL-3.0"
version = "0.0.1"
authors = ["Aleksey Bekh-Ivanov <6ex@mail.ru>"]
include = [
    "src/*.rs",
    "Cargo.toml",
]

[dependencies]
