[package]
name = "smartcrop"
description="Clone of smartcrop library in JavaScript"
license="GPL-3.0"
version = "0.0.1"
authors = ["Aleksey Bekh-Ivanov <6ex@mail.ru>"]
include = [
    "src/*.rs",
    "Cargo.toml",
]

[features]
default =["image"]
compare-to-js=[]

[dependencies]
image = { version = "*", optional = true }

[dev-dependencies]
proptest = "^0.7.0"
serde = "1.0.55"
serde_json = "*"
serde_derive = "*"